services:
  app:
    hostname: theatre-app
    build:
      context: . 
      dockerfile: docker/dev/app/Dockerfile
    volumes:
      - ./app/:/opt/app/
      - postgres_socket:/postgres_socket
    ports:
      - "8000:8000"
    env_file:
      - docker/dev/env/.env
      - docker/dev/env/.db.env
    depends_on: [db, ]
    restart: unless-stopped
    networks:
      - theatre_network

  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
      - postgres_socket:/var/run/postgresql/
    env_file:
      - docker/dev/env/.db.env
    networks:
      - theatre_network

volumes:
  postgres_data:
  postgres_socket:

networks:
  theatre_network:
    driver: bridge
