# version: '3'
services:
  app:
    hostname: theatre-app
    build:
      context: .
      dockerfile: docker/prod/app/Dockerfile
    volumes:
      # - ./app/:/opt/app/
      - postgres_socket:/postgres_socket
      - media:/opt/app/media/
    depends_on: [db, ]
    ports:
      - "8000:80"
    env_file:
      - docker/prod/env/.db.env
      - docker/prod/env/.env
      - docker/prod/env/.gunicorn.env
    restart: unless-stopped
    networks:
      - theatre_network

  db:
    image: postgres:15.1-alpine
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
      - postgres_socket:/var/run/postgresql/
    env_file:
      - docker/prod/env/.db.env
    restart: always
    networks:
      - theatre_network

volumes:
  postgres_data:
  postgres_socket:
  media:

networks:
  theatre_network:
    driver: bridge
