# Generated by Django 5.0.4 on 2024-09-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_create_superuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filmwork',
            table='content"."film_work',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='content"."genre',
        ),
        migrations.AlterModelTable(
            name='genrefilmwork',
            table='content"."genre_film_work',
        ),
        migrations.AlterModelTable(
            name='person',
            table='content"."person',
        ),
        migrations.AlterModelTable(
            name='personfilmwork',
            table='content"."person_film_work',
        ),
    ]
